import { PartnerProvider } from "@/context/PartnerContext";
import { WaterBillingProvider } from "@/context/WaterBillingContext";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto_init = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto_init.variable} bg-gray-100 font-roboto`}>
        <PartnerProvider>
          <WaterBillingProvider>{children}</WaterBillingProvider>
        </PartnerProvider>
      </body>
    </html>
  );
}
